In [1]:
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 200)
pd.set_option('display.max_columns', None)

In [13]:
# Radi Bois
#trans_path = './releves/mouvement_rb_3.5-to-8.5.xls'
#trans_path = './releves/mouvement_rb_9.5-to-22.5.xls'
trans_path = './releves/mouvement_nr_10.5-to-22.5.xls'
cheques_path = './releves/nr_cheques-20.5.txt'

# Nezha
#trans_path = './releves/mouvement_nr_23.4-to-9.5.xls'
#cheques_path = './releves/nr_cheques.txt'

In [22]:
# Read data from xls file
df_trans = pd.read_csv(trans_path, 
        delimiter="\t", skiprows=8, skipfooter=2, engine='python')
# Drop date_Valeur column and Debit column
df_trans = df_trans.drop(['date_Valeur', 'Debit'], axis=1)
df_trans.Libelle = df_trans.Libelle.astype(str)

print("Bank Transactions:", df_trans.shape[0])
df_trans = df_trans.sort_values('DateOperation')
df_trans.style.set_properties(subset=["Libelle"],**{'text-align': 'left'})

Bank Transactions: 16

In [33]:
df_cheques = pd.read_csv(cheques_path, dtype=str)
df_cheques.amount = df_cheques.amount.astype(int)
print("Cheques:", df_cheques.shape[0])
df_cheques

Cheques: 21

   chequeNo  amount
0   0699161       0
1   2275879       0
2   0740911       0
3   2100785       0
4   0699207       0
5   9533546       0
6   0699250       0
7   2100005       0
8   0935166       0
9   1300040       0
10  0224806       0
11  9533547       0
12  6918683       0
13  0699208       0
14  1800069       0
15  9478120       0
16  2476206       0
17  0699251       0
18  4663824       0
19  0699209       0
20  9533548       0

In [41]:
# Lookup the df_cheques.chequeNo in the df_trans.Libelle column
# and return the corresponding Libelle
#result = df_trans[df_trans['Libelle'].str.contains('|'.join(df_cheques['chequeNo'].astype(str)))] #['Libelle']
#print(result)
df_trans['chequeNo'] = df_trans['Libelle'].str.extract(r'(\d*\.\d+|\d+)', expand=False) #.fillna(0).astype(int) 

#df_cheques['chequeNo'] = df_cheques['chequeNo'].astype(int)

# Concat df_cheques with df_trans
df_merged = df_cheques.merge(df_trans, 'outer').sort_values('DateOperation')
# Select rows where amount is NaN
print("VA Cheques:")
display(df_merged[df_merged['amount'].isnull()])

# Select rows where DateOperation is NaN
print("Unpaid cheques:")
display(df_merged[df_merged['DateOperation'].isnull()]["chequeNo"])

# Select rows where DateOperation is NaN
print("Paid cheques:", df_merged[df_merged['DateOperation'].notna()].shape[0])
display(df_merged[df_merged['DateOperation'].notna()])

VA Cheques:

Empty DataFrame
Columns: [chequeNo, amount, DateOperation, Libelle, Credit]
Index: []

Unpaid cheques:

6     0699250
9     1300040
10    0224806
15    9478120
18    4663824
Name: chequeNo, dtype: object

Paid cheques: 16

,chequeNo,amount,DateOperation,Libelle,Credit
5,9533546,0,2024-05-10,ENC CHQ 9533546 MENNIOUI MOHAMMED,10000.0
0,0699161,0,2024-05-14,ENC CHEQUE 0699161 ATTIZITI SOFIANE,20500.0
1,2275879,0,2024-05-14,ENC CHEQUE 2275879 EL BENNAR EL HOUSSAINE,15200.0
2,0740911,0,2024-05-14,ENC CHEQUE 0740911 SLAH ABDELATIF,11934.0
3,2100785,0,2024-05-14,ENC CHEQUE 2100785 MOHAMED EL MOUIKINI,25000.0
4,0699207,0,2024-05-14,ENC CHEQUE 0699207 ATTIZITI SOFIANE,16000.0
11,9533547,0,2024-05-14,ENC CHQ 9533547 MENNIOUI MOHAMMED,10000.0
7,2100005,0,2024-05-16,ENC CHEQUE 2100005 BACHAR ISMAIL,5000.0
8,0935166,0,2024-05-16,ENC CHEQUE 0935166 BERZAKHE FOUAD,10625.0
12,6918683,0,2024-05-16,ENC CHEQUE 6918683 MOUHSINE OUAKKI,27195.0
13,0699208,0,2024-05-16,ENC CHEQUE 0699208 ATTIZITI SOFIANE,16000.0
14,1800069,0,2024-05-16,ENC CHEQUE 1800069 MOHAMMED ALAMI,15000.0
20,9533548,0,2024-05-16,ENC CHQ 9533548 MENNIOUI MOHAMMED,10000.0
16,2476206,0,2024-05-20,ENC CHEQUE 2476206 BOUARGALNE LAHCEN,4450.0
17,0699251,0,2024-05-20,ENC CHEQUE 0699251 ATTIZITI SOFIANE,20500.0
19,0699209,0,2024-05-20,ENC CHEQUE 0699209 ATTIZITI SOFIANE,16000.0

### Mois 5 - Nezha
From Alaoui:
6     0699250 => Deposited 22.5.2024
9     1300040 => Returned then Deposited 23.5.2024
10    0224806 => Panadoor paid
15    9478120 => Panadoor paid
18    4663824 => Panadoor paid

	chequeNo	amount	DateOperation	Libelle	Credit \
8	224806	NaN	2024-05-16	ENC CHEQUE 0224806 HICHAM ANBI	23000 \
9	9478120	NaN	2024-05-16	ENC CHEQUE 9478120 ES-SALHI MOHAMED	42800 \
10	4663824	NaN	2024-05-20	ENC CHEQUE 4663824 STE AJI TRADIVE	8800 

#### 5     9433427 => Received cash 
DateOperation	Libelle	Credit	Facture No	Cheque No \
9876378 => 07/05/2024	ENC CHEQUE 9876378 MANARA POLYGRAF	20760	FA20240154	9876378 \
0891025 => 07/05/2024	ENC CHEQUE 0891025 STE PRIDELQUA MAROC SARL AU	11000	FA20240161	0891025 \
9193851 => 07/05/2024	ENC CHEQUE 9193851 NINOS SCHOOL	5000	FA20240162	9193851

In [43]:
%pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl (69 kB)
   ---------------------------------------- 0.0/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----------------- ---------------------- 30.7/69.3 kB 131.3 kB/s eta 0:00:01
   ----------------------------------- ---- 61.4/69.3 kB 233.8 kB/s eta 0:00:01
   ---------------------------------------- 69.3/69.3 kB 236.1 kB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.1.0
Note: you may need to restart the kernel to use updated packages.

In [52]:

import pyodbc
import pandas as pd
# Some other example server values are
# server = 'localhost\sqlexpress' # for a named instance
# server = 'myserver,port' # to specify an alternate port
server = 'MCOEFLAE1250401' 
database = 'Panadoor' 
username = 'dbuser' 
password = 'pass123'  
conn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = conn.cursor()
# select 26 rows from SQL table to insert in dataframe.
query = "Select * from dbo.F_COMPTET"
df = pd.read_sql(query, conn)
display(df.head(26))

C:\Users\erradi\AppData\Local\Temp\ipykernel_17292\1110947426.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,CT_Num,cbCT_Num,CT_Intitule,CT_Type,CG_NumPrinc,cbCG_NumPrinc,CT_Qualite,CT_Classement,cbCT_Classement,CT_Contact,CT_Adresse,CT_Complement,CT_CodePostal,cbCT_CodePostal,CT_Ville,CT_CodeRegion,CT_Pays,CT_Raccourci,cbCT_Raccourci,BT_Num,N_Devise,CT_Ape,CT_Identifiant,CT_Siret,CT_Statistique01,CT_Statistique02,CT_Statistique03,CT_Statistique04,CT_Statistique05,CT_Statistique06,CT_Statistique07,CT_Statistique08,CT_Statistique09,CT_Statistique10,CT_Commentaire,CT_Encours,CT_Assurance,CT_NumPayeur,cbCT_NumPayeur,N_Risque,CO_No,cbCO_No,N_CatTarif,CT_Taux01,CT_Taux02,CT_Taux03,CT_Taux04,N_CatCompta,N_Period,CT_Facture,CT_BLFact,CT_Langue,N_Expedition,N_Condition,CT_Saut,CT_Lettrage,CT_ValidEch,CT_Sommeil,DE_No,cbDE_No,CT_ControlEnc,CT_NotRappel,N_Analytique,cbN_Analytique,CA_Num,cbCA_Num,CT_Telephone,CT_Telecopie,CT_EMail,CT_Site,CT_Coface,CT_Surveillance,CT_SvDateCreate,CT_SvFormeJuri,CT_SvEffectif,CT_SvCA,CT_SvResultat,CT_SvIncident,CT_SvDateIncid,CT_SvPrivil,CT_SvRegul,CT_SvCotation,CT_SvDateMaj,CT_SvObjetMaj,CT_SvDateBilan,CT_SvNbMoisBilan,N_AnalytiqueIFRS,cbN_AnalytiqueIFRS,CA_NumIFRS,CT_PrioriteLivr,CT_LivrPartielle,MR_No,cbMR_No,CT_NotPenal,EB_No,cbEB_No,CT_NumCentrale,cbCT_NumCentrale,CT_DateFermeDebut,CT_DateFermeFin,CT_FactureElec,CT_TypeNIF,CT_RepresentInt,CT_RepresentNIF,CT_EdiCodeType,CT_EdiCode,CT_EdiCodeSage,CT_ProfilSoc,CT_StatutContrat,CT_DateMAJ,CT_EchangeRappro,CT_EchangeCR,PI_NoEchange,cbPI_NoEchange,CT_BonAPayer,CT_DelaiTransport,CT_DelaiAppro,CT_LangueISO2,CT_AnnulationCR,CT_Facebook,CT_LinkedIn,CT_ExclureTrait,CT_GDPR,CT_Prospect,CT_OrderDay01,CT_OrderDay02,CT_OrderDay03,CT_OrderDay04,CT_OrderDay05,CT_OrderDay06,CT_OrderDay07,CT_DeliveryDay01,CT_DeliveryDay02,CT_DeliveryDay03,CT_DeliveryDay04,CT_DeliveryDay05,CT_DeliveryDay06,CT_DeliveryDay07,CAL_No,cbCAL_No,cbProt,cbMarq,cbCreateur,cbModification,cbReplication,cbFlag,cbCreation,cbCreationUser
0,44110001,b'44110001',Emirates Panel Manufacture LLC,1,44110000,b'44110000',,EPM,b'EPM',,,,,b'',,,Émirats Arabes Unis,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,44110001,b'44110001',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,http://www.epm-uae.com/,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,0,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,1,COLU,2021-11-30 23:12:01,0,0,2021-08-28 01:23:16,188B9047-64F0-46A9-A1DA-749D41302EEA
1,34210001,b'34210001',Ste Netale Allu,0,34210000,b'34210000',,Netale,b'Netale',,,,,b'',,,,,b'',0,0,,ICE: 00263123500003,,,,,,,,,,,,,0.0,0.0,34210001,b'34210001',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,3,COLU,2021-08-28 21:49:12,0,0,2021-08-28 04:08:47,188B9047-64F0-46A9-A1DA-749D41302EEA
2,34210002,b'34210002',Ste Tiziti Aluminium,0,34210000,b'34210000',,Ste Tiziti Alumin,b'Ste Tiziti Alumin',,,,,b'',,,,,b'',0,0,,ICE: 002551437000019,,,,,,,,,,,,,0.0,0.0,34210002,b'34210002',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,4,COLU,2022-07-08 20:59:22,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
3,34210003,b'34210003',Ste Verre Oulad Chaker,0,34210000,b'34210000',,Oulad Chaker,b'Oulad Chaker',,,,,b'',,,,,b'',0,0,,ICE: 002299347000056,,,,,,,,,,,,,0.0,0.0,34210003,b'34210003',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,5,COLU,2021-12-29 18:47:32,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
4,34210004,b'34210004',Hamid El Hasny,0,34210000,b'34210000',,Hasny,b'Hasny',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210004,b'34210004',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,6,COLU,2021-08-28 21:49:51,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
5,34210005,b'34210005',Mouhsine Ouakki,0,34210000,b'34210000',,Mouhsine Ouakki,b'Mouhsine Ouakki',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210005,b'34210005',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,7,COLU,2022-04-14 01:04:26,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
6,34210006,b'34210006',Abdechafiq Massoudi,0,34210000,b'34210000',,Massoudi,b'Massoudi',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210006,b'34210006',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,8,COLU,2021-08-28 21:50:32,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
7,34210007,b'34210007',Abdelaziz Omari,0,34210000,b'34210000',,Omari,b'Omari',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210007,b'34210007',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,9,COLU,2021-08-28 21:50:52,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
8,34210008,b'34210008',Mohamed El Ouardy,0,34210000,b'34210000',,Ouardy,b'Ouardy',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210008,b'34210008',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,10,COLU,2021-08-28 21:51:12,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
9,34210009,b'34210009',El Arabi El Abid,0,34210000,b'34210000',,El Arabi El Abid,b'El Arabi El Abid',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210009,b'34210009',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,11,COLU,2022-08-06 14:12:11,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
10,34210010,b'34210010',Ste Delta Line,0,34210000,b'34210000',,Delta,b'Delta',,,,,b'',,,,,b'',0,0,,ICE: 000205763000074,,,,,,,,,,,,,0.0,0.0,34210010,b'34210010',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,12,COLU,2021-08-28 21:52:06,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
11,34210011,b'34210011',Ste Keniglass,0,34210000,b'34210000',,Ste Keniglass,b'Ste Keniglass',,,,,b'',,,,,b'',0,0,,ICE: 002322357000071,,,,,,,,,,,,,0.0,0.0,34210011,b'34210011',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,0,0,None,0,0,0,,0,,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,13,COLU,2022-04-14 01:06:47,0,0,2021-08-28 04:08:48,188B9047-64F0-46A9-A1DA-749D41302EEA
12,34210012,b'34210012',Ste Promo Saad,0,34210000,b'34210000',,Promo,b'Promo',,,,,b'',,,,,b'',0,0,,ICE: 001819682000056,,,,,,,,,,,,,0.0,0.0,34210012,b'34210012',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,14,COLU,2021-08-30 00:42:15,0,0,2021-08-30 00:42:15,188B9047-64F0-46A9-A1DA-749D41302EEA
13,34210013,b'34210013',Ste Frolum Group,0,34210000,b'34210000',,Frolum,b'Frolum',,,,,b'',,,,,b'',0,0,,ICE 000231642000032,,,,,,,,,,,,,0.0,0.0,34210013,b'34210013',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,15,COLU,2021-08-30 00:57:16,0,0,2021-08-30 00:57:16,188B9047-64F0-46A9-A1DA-749D41302EEA
14,34210014,b'34210014',Ste Verre Acherafae,0,34210000,b'34210000',,St Verre Acherafa,b'St Verre Acherafa',,,,,b'',,,,,b'',0,0,,ICE: 001561037000053,,,,,,,,,,,,,0.0,0.0,34210014,b'34210014',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,16,COLU,2022-08-06 14:15:32,0,0,2021-09-06 21:37:25,188B9047-64F0-46A9-A1DA-749D41302EEA
15,34210015,b'34210015',Ste Guedira.Tex,0,34210000,b'34210000',,Ste Guedira Tex,b'Ste Guedira Tex',,,,,b'',,,,,b'',0,0,,ICE: 001753289000010,,,,,,,,,,,,,0.0,0.0,34210015,b'34210015',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,17,COLU,2021-10-06 01:45:33,0,0,2021-10-06 01:19:36,188B9047-64F0-46A9-A1DA-749D41302EEA
16,34210016,b'34210016',Ste Lina Sud,0,34210000,b'34210000',,Ste Lina Sud,b'Ste Lina Sud',,,,,b'',,,,,b'',0,0,,ICE: 001838946000042,,,,,,,,,,,,,0.0,0.0,34210016,b'34210016',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,18,COLU,2021-10-06 01:37:08,0,0,2021-10-06 01:37:08,188B9047-64F0-46A9-A1DA-749D41302EEA
17,34210017,b'34210017',Ste Industrie Marocaine Du Verre,0,34210000,b'34210000',,Industrie DuVerre,b'Industrie DuVerre',,,,,b'',,,,,b'',0,0,,ICE: 001769103000026,,,,,,,,,,,,,0.0,0.0,34210017,b'34210017',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,19,COLU,2021-10-06 02:00:39,0,0,2021-10-06 02:00:39,188B9047-64F0-46A9-A1DA-749D41302EEA
18,34210018,b'34210018',Ste Nord 2P Travaux,0,34210000,b'34210000',,Nord 2P Travaux,b'Nord 2P Travaux',,,,,b'',,,,,b'',0,0,,ICE: 000040582000095,,,,,,,,,,,,,0.0,0.0,34210018,b'34210018',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,20,COLU,2021-10-06 02:29:11,0,0,2021-10-06 02:29:11,188B9047-64F0-46A9-A1DA-749D41302EEA
19,34210019,b'34210019',Ste Sogercos,0,34210000,b'34210000',,Sogercos,b'Sogercos',,,,,b'',,,,,b'',0,0,,ICE: 001935691000040,,,,,,,,,,,,,0.0,0.0,34210019,b'34210019',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,21,COLU,2021-11-07 22:53:29,0,0,2021-11-07 22:53:24,188B9047-64F0-46A9-A1DA-749D41302EEA
20,44110002,b'44110002',Carburo del Cinca SA,1,44110000,b'44110000',,Carburo,b'Carburo',,,,,b'',,,Espagne,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,44110002,b'44110002',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,https://www.carburodelcinca.com/,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,0,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,22,COLU,2021-11-30 23:11:28,0,0,2021-11-30 23:11:28,188B9047-64F0-46A9-A1DA-749D41302EEA
21,34210020,b'34210020',Ste Construction Euro Catalonia,0,34210000,b'34210000',,ConstructionEuro,b'ConstructionEuro',,,,,b'',,,,,b'',0,0,,ICE: 000085700000035,,,,,,,,,,,,,0.0,0.0,34210020,b'34210020',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,23,COLU,2021-12-29 17:55:48,0,0,2021-11-30 23:30:22,188B9047-64F0-46A9-A1DA-749D41302EEA
22,34210021,b'34210021',Jamal Frit,0,34210000,b'34210000',,Jamal Frit,b'Jamal Frit',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210021,b'34210021',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,24,COLU,2022-05-13 23:12:16,0,0,2021-11-30 23:33:35,188B9047-64F0-46A9-A1DA-749D41302EEA
23,34210022,b'34210022',Ste Belmekki Hassan et Fils,0,34210000,b'34210000',,Belmekki,b'Belmekki',,,,,b'',,,,,b'',0,0,,ICE: 001530615000051,,,,,,,,,,,,,0.0,0.0,34210022,b'34210022',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,25,COLU,2021-12-29 17:55:21,0,0,2021-12-29 17:55:20,188B9047-64F0-46A9-A1DA-749D41302EEA
24,34210023,b'34210023',Khalid Alami,0,34210000,b'34210000',,Khalid Alami,b'Khalid Alami',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210023,b'34210023',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,26,COLU,2022-04-14 00:17:49,0,0,2022-02-04 01:27:13,188B9047-64F0-46A9-A1DA-749D41302EEA
25,34210024,b'34210024',Nejjar,0,34210000,b'34210000',,Nejjar,b'Nejjar',,,,,b'',,,,,b'',0,0,,,,,,,,,,,,,,,0.0,0.0,34210024,b'34210024',1,0,None,1,0.0,0.0,0.0,0.0,1,1,1,0,0,1,1,1,1,0,0,0,None,0,0,0,None,None,b'',,,,,,0,1753-01-01,,,0.0,0.0,0,1753-01-01,0,,,1753-01-01,,1753-01-01,0,0,None,None,0,0,0,None,0,0,None,None,b'',1753-01-01,1753-01-01,0,0,,,0,,,0,0,1753-01-01,0,1,0,None,0,0,0,,1,,,0,0,0,1,1,1,1,1,0,0,1,1,1,1,1,0,0,2,2.0,0,27,COLU,2022-02-04 01:55:08,0,0,2022-02-04 01:55:07,188B9047-64F0-46A9-A1DA-749D41302EEA